version: "3.7"
services:
    db:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres123
        ports:
            - 5432:5432
        volumes:
            - db-java-data:/var/lib/postgresql/data
        networks:
            bridge:
            default:
                aliases:
                    - postgres

    dt-api:
        image: pawbal96/dt-api-java
        labels:
            - "traefik.http.routers.dt-api.rule=PathPrefix(`/api`, `/swagger`, `/webjars`, `/csrf`, `/v2`)"
        networks:
            - bridge
            - default
        configs:
            - source: properties
              target: /app/application.properties

    dt-app:
        image: pawbal96/dt-app
        labels:
            - "traefik.http.routers.dt-app.rule=PathPrefix(`/`)"
        networks:
            - bridge

    reverse-proxy:
        image: traefik:v2.0
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command:
            - --providers.docker

volumes:
    db-java-data:
networks:
    bridge:
        external: true
        name: bridge
    default:
configs:
    properties:
        external: true
        name: dt-java-api-properties
