version: "3.7"
services:
    db:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres123
        ports:
            - 5432:5432
        volumes:
            - db-net-data:/var/lib/postgresql/data
        networks:
            bridge:
            default:
                aliases:
                    - postgres

    dt-api:
        image: pawbal96/dt-api-net
        ports:
            - 8080:80
        networks:
            - bridge
            - default

    dt-app:
        image: pawbal96/dt-app
        ports:
            - 80:8080
        networks:
            - bridge

volumes:
    db-net-data:
networks:
    bridge:
        external: true
        name: bridge
    default:
