version: "3.7"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - db-net-data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres

  dt-api:
    image: pawbal96/dt-api-net
    labels:
      - "traefik.http.routers.dt-api.rule=PathPrefix(`/api`, `/swagger`)"
    networks:
      - bridge
      - default
    configs:
      - source: dt-api-net-properties
        target: /app/appsettings.json

  dt-app:
    image: pawbal96/dt-app
    labels:
      - "traefik.http.routers.dt-app.rule=PathPrefix(`/`)"
    networks:
      - bridge
    configs:
      - source: dt-app-properties
        target: /usr/local/tomcat/webapps/ROOT/assets/runtimeConfig.json

  reverse-proxy:
    image: traefik:v2.0
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker

volumes:
  db-net-data:
networks:
  bridge:
    external: true
    name: bridge
  default:
configs:
  dt-api-net-properties:
    external: true
    name: dt-api-net-properties
  dt-app-properties:
    external: true
    name: dt-app-properties
