version: "3.7"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=dt
    volumes:
      - db-traffic-generator-data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - traffic-generator-postgres

  dt-traffic-generator:
    image: pawbal96/dt-traffic-generator
    labels:
      - "traefik.http.routers.dt-traffic-generator.rule=PathPrefix(`/testapi`, `/dt-traffic-generator/swagger`)"
      - "traefik.docker.network=daytrader"
    networks:
      - default
      - daytrader
    configs:
      - source: dt-traffic-generator-properties
        target: /app/appsettings.json

volumes:
  db-traffic-generator-data:
networks:
  default:
  daytrader:
    external: true
configs:
  dt-traffic-generator-properties:
    external: true
